# Generated by Django 3.1.2 on 2020-10-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201021_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='r_narula', on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
